### ISSUE TITLE
Docker Container Stops Running

### ISSUE THREAD

**Issue by daNutzzzzz** [Audionut/Upload-Assistant#521]
Hi,

I'm running this in docker on "**Ubuntu 24.04.2 LTS**" but I'm having an issue where i start it and it stops, this means I'm unable to exec into it and run any relevant commands.

**Logs**
```
Error during terminal reset: I/O operation on closed file
Error during terminal reset: I/O operation on closed file
```

Obviously i can issue a command in the compose file but this means i have to edit the compose file each time and then re-create the container.

**compose**
```
    uploadarr:
        container_name: uploadarr
        hostname: uploadarr
        stdin_open: true
        tty: true
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=Europe/London'
        network_mode: host
        volumes:
            - /mnt/ssd1/docker/docker-data/uploadarr/config.py:/Upload-Assistant/data/config.py
            - NAS-01-Multimedia:/downloads # Media Files
            - /mnt/ssd1/docker/docker-data/qbittorrent/config/qBittorrent/BT_backup:/BT_backup
            - /mnt/HDD3TB-1/download/qbittorrent/upload:/Upload-Assistant/upload
#        restart: unless-stopped
        image: ghcr.io/audionut/upload-assistant:latest
```

**docker version**
```
Client: Docker Engine - Community
 Version:           28.0.0
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        f9ced58
 Built:             Wed Feb 19 22:10:30 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.0
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       af898ab
  Built:            Wed Feb 19 22:10:30 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
